version: '3'
services:
  # Expose worker-tikaextract admin port so it may be queried externally and increase log level.
  worker-tikaextract:
    ports:
      - "5005:8081"
    environment:
      CAF_LOG_LEVEL: DEBUG
